### ISSUE TITLE
Improve pattern matching

### ISSUE THREAD

**Issue by QtRoS** [xpacks/chan-fatfs#8]
Hello!

I've been studied project's source code for a while and discovered `pattern_matching` function. Seems that it uses recursion to check if filename matches mask. In my experience it's not effective way for tricky patterns, which is also hard to prove algorithmically. Recently I've open-sourced my tiny wildcard matching library: https://github.com/QtRoS/wildest-card. It implements pattern matching with very fast and compact NFA implementation, zero allocations (only 64 bytes are allocated statically on stack, enough for pattern of 256 characters) and no recursion.  

Maybe you will find it useful.

**Comment by ilg-ul** [comment]
Thank you, but this repo is deprecated. Please contribute to the upstream project.
